export const Strings = {
    DASHBOARD: "Dashboard",
    LOGIN: "Login",
    SIGNUP: "Signup",
    SEARCH: "Search",
    OR: "or",
    TYPE_A_COMMAND: "Type a command",
    ADD_PRODUCT: "Add Product",
    NEW_CUSTOMERS: "New Customers",
    TOTAL_CUSTOMERS: "Total Customers",
    COMMENTS: "Comments",
    CUSTOMERS: "Customers",
    PRODUCTS: "Products",
    REFUND_REQUESTS: "Refund Requests",
    POPULAR_PRODUCTS: "Popular Products",
    RECENT_PRODUCTS: "Recent Products",
    GET_MORE_CUSTOMERS: "Get More Customers",
    FACEBOOK: "Facebook",
    TWITTER: "Twitter",
    INSTAGRAM: "Instagram",
    RETURNING_CUSTOMERS: "Returning Customers",
    WELCOME: "Welcome",
    PERSONAL_MESSAGE: "Personal Message",
    GET_HELP: "Get Help",
    SEND_MESSAGE: "Send Message",
    PRO_TIPS: "Pro Tips",
    PRODUCT_NAME: "Product Name",
    PRODUCT_CATEGORY: "Product Category",
    PRODUCT_PRICE: "Product Price",
    PRODUCT_IMAGE: "Product Image",
    PRODUCT_DESCRIPTION: "Product Description",
}
export const NAVIGATION = {
    DASHBOARD: "Dashboard",
    PRODUCT: "Product",
    ANALYTICS: "Analytics",
    DRAFTS: "Drafts",
    RELEASED: "Released",
    COMMENTS: "Comments",
    SCHEDULED: "Scheduled",
    CUSTOMERS: "Customers",
    STORE: "Store",
    REVENUE: "Revenue",
    DISCOUNTS: "Discounts",
}
export const ROUTES = {
    ROOT_PATH: "/",
    DASHBOARD: "/dashboard",
}
